// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vlnuhefopurefbkksxnd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZsbnVoZWZvcHVyZWZia2tzeG5kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4ODM2NjgsImV4cCI6MjA3MjQ1OTY2OH0.m5ZZ0ChTibG1T_wg6vmHBtv_b1B4NoDxlMFXELtS1e0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});